### ISSUE TITLE
[FEAT] 갤러리 권한 로직 수정 및 알람 권한 추가

### ISSUE THREAD

**Issue by suminhan123** [Central-MakeUs/Youngduck-Client#104]
## 어떤 작업인지 설명해주세요
갤러리 권한 로직 수정
알람 권한 추가 및 설정 on/off 기능

## TODO
- [x] 로그인 토큰 재발급 로직 수정
- [x] 갤러리 권한 로직 수정
- [x] 알람 권한 추가 및 설정 on/off 기능
