### ISSUE TITLE
[FIX] 1차 QA UI 피드백 반영

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#111]
## TODO
- [x] keyword percentage 0일 때 비율 차지하는 UI 수정
- [x] 약관동의 할 때 세 가지 항목 다 선택 시 체크버튼으로, 필수 두 가지 선택하면 가운데 줄 이모티콘으로 수정
- [x] 바텀 네비게이션 하단 간격 수정
- [x] text area style 수정
- [x] 일부 이미지 비율 변경 및 이미지 없을 시 default 이미지 설정
- [x] 팝콘파티 - 상세 - 리뷰, 더 보기 버튼 사이 divider 추가
- [x] 영화 찾기 bottom sheet를 약관 동의 bottom sheet처럼 style 수정
