### ISSUE TITLE
[FIX] 1차 QA 스크리닝 수정 작업

### ISSUE THREAD

**Issue by suminhan123** [Central-MakeUs/Youngduck-Client#112]
## 어떤 작업인지 설명해주세요
1차 QA 스크리닝 수정 작업

## TODO
- [x] 스크리닝 닉네임 빈 닉네임
- [x] 리뷰 활성화 기간을 상영회 시작일 수정
- [x] 디테일 하단 버튼 고정 수정
- [x] 디테일 하단에 상태가 complete 일 때 tooltip 보여주기
- [x] 웹뷰 두번 들어갈 시 안들어가지는 오류 & focus 로 로직 수정
- [x] 상단 타이틀 수정
- [x] 리뷰 작성하기 text 아쉬웠던 점으로 수정
- [x] 스크리닝 전화번호 안보이는 문제 수정
- [x] disabled 버튼 컬러 수정
