### ISSUE TITLE
[FIX] 1차 QA 팝콘파티 API 수정

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#115]
## TODO
- [x] 팝콘작 추천하기 body에 movieType 추가하기
- [x] 영화 추천 혹은 리뷰하고 돌아왔을 때 데이터 최신화
- [x] 팝콘파티에서 쓰이는 mutation 한 곳으로 모으기
