### ISSUE TITLE
[FIX] 일부 UI 수정

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#123]
## TODO
- [x] 팝콘작 투표하기 스크린 top bar → back title top bar로 수정
- [ ] 팝콘작 리뷰하기 bottom button → floating bottom button으로 바꾸기
- [x] 로그인 화면 '팝콘메이트', backgorund 팝콘 이미지 수정 
- [x] 회원가입 화면에서 handle gesture false 설정하기
