### ISSUE TITLE
[FEAT] 마이페이지 유저 정보 API 연동

### ISSUE THREAD

**Issue by suminhan123** [Central-MakeUs/Youngduck-Client#133]
## 어떤 작업인지 설명해주세요
마이페이지 유저 정보 API 연동

## TODO
- [x] 유저 정보 api
- [x] 유저 장르 api
- [x]  마케팅 on/off api
