### ISSUE TITLE
[FIX] 2차 QA 스크리닝 피드백 반영

### ISSUE THREAD

**Issue by suminhan123** [Central-MakeUs/Youngduck-Client#144]
## 어떤 작업인지 설명해주세요
2차 QA 스크리닝 피드백 반영

## TODO
- [x] 작성하기 페이지, 리뷰 페이지, 웹뷰 safeAreaview , 아래 inset padding 주기
- [x] 스크리닝 목록 키보드 내려가게 (스크리닝 목록)
- [x] input 컴포넌트 관람 신청 url, 주최 이메일 focus 해제 안되는 문제 (스크리닝 작성하기)
- [x] 작성하기 할 때 버튼 로딩 중 표시 (스크리닝 상세 리뷰 작성하기)
- [x] 검색할 때는 default 를 전체로 갈 수 있게  (스크리닝 목록)
