### ISSUE TITLE
[FIX] 3차 QA 이후 UI 수정

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#149]
## TODO
- [x] 상영회 상세 스크린 바텀 버튼 style 수정
- [x] text input style 수정
- [x] 팝콘파티 배너 text 수정
- [x] 탈퇴 '사용성이 불편해요' 변수명 바꾸기
