### ISSUE TITLE
[FIX] 스크리닝 상세, 리뷰 페이지 수정사항 반영

### ISSUE THREAD

**Issue by suminhan123** [Central-MakeUs/Youngduck-Client#158]
## 어떤 작업인지 설명해주세요
스크리닝 상세, 리뷰 페이지 수정사항 반영

## TODO
- [x] 스크리닝 목록 키보드 내려가게 설정
- [x] 리뷰하기 첫 페이지 버튼 내려감
- [x] 스크리닝 검색 옵션 상수 변경
- [x] 마이페이지 마케팅 버튼
