### ISSUE TITLE
[FIX] 4차 QA 회원가입, 팝콘파티, 마이페이지 피드백 반영

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#159]
## TODO
- [x] 회원가입 시 최소 1개 ~ 최대 5개 선택 및 워딩 변경
- [x] 이번 주 팝콘작 default 이미지가 작음
- [x] 마이페이지 워딩 변경
- [x] font 파일 변경
