### ISSUE TITLE
[FIX] 출시 전 미흡한 UI 수정

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#179]
## TODO
- [x] 회원가입 시 마케팅 동의 여부 보내주기
- [x] 스크리닝 리뷰하기 section간 거리가 넓음
- [x] 스크리닝 리뷰 후 상영지수 최신화하기
- [x] 팝콘작 검색하기 input 글씨 밑으로 내려가있는 style 수정
- [x] 스크리닝 작성하기 바텀 버튼 floating으로 수정
- [x] 회원가입 약관동의 바텀 시트 문구 수정 및 웹뷰 연결
