### ISSUE TITLE
[FIX] 워딩 및 컴포넌트 수정

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#181]
## TODO
- [x] 약관 동의 font style 변경
- [x] 마케팅 약관 동의 워딩 변경
- [x] search component 수정
