### ISSUE TITLE
[FIX] 배포 후 자잘한 오류 해결

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#187]
## TODO
- [x] 닉네임 input 시 2글자에서도 warning 뜨는 오류
- [x] 팝콘파티 홈에서 스켈레톤 넣기
- [x] 기기에서 글씨 크기 크게할 경우 UI 깨지는 현상 해결
