### ISSUE TITLE
[FIX] 버전 1.0.6 UI 수정 사항

### ISSUE THREAD

**Issue by gs0428** [Central-MakeUs/Youngduck-Client#194]
## TODO
- [x] 나의 스크리닝 통계하단 부분 버튼 UI 수정
- [x] input 컴포넌트 style 수정
- [x] custom text input 로직 수정
