### ISSUE TITLE
[REFACTOR] textInput 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by suminhan123** [Central-MakeUs/Youngduck-Client#31]
## 어떤 작업인지 설명해주세요
textInput 컴포넌트 리팩토링 및 공통 스타일 text Area 컴포넌트 적용

## TODO
- [x] textInput option 추가
- [x] 공통 스타일 관리
- [x] textArea 컴포넌트 적용
