### ISSUE TITLE
[UI] 스크리닝 상세 퍼블리싱

### ISSUE THREAD

**Issue by suminhan123** [Central-MakeUs/Youngduck-Client#41]
## 어떤 작업인지 설명해주세요
스크리닝 상세 퍼블리싱

## TODO
- [x] 스크리닝 상세 스크리닝 정보 퍼블리싱
- [x] 공통 컴포넌트 카테고리
- [x] 공통 컴포넌트 bottom button
- [x] 스크리닝 상세 리뷰 퍼블리싱
