### ISSUE TITLE
[FEAT] 상영회 관람 알람 기능

### ISSUE THREAD

**Issue by suminhan123** [Central-MakeUs/Youngduck-Client#74]
## 어떤 작업인지 설명해주세요
상영회 관람 알람 기능

## TODO
- [x] android 환경 세팅
- [x] ios 환경 세팅
- [x] 알람 기능 구현
- [x] 서버 알람 api 연결
